[package]
name = "bitflag-attr"
authors = ["GrayJack <gr41.j4ck@gmail.com>"]
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A macro to generate bitflags structures from C-like enums"
keywords = ["bit", "bitmask", "bitflags", "flags"]
categories = ["no-std"]
repository = "https://github.com/GrayJack/bitflag-attr"
homepage = "https://github.com/GrayJack/bitflag-attr"
rust-version = "1.70.0"
exclude = ["/tests", "/.github"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = [
    "full",
    "parsing",
    "printing",
    "proc-macro",
], default-features = false }
quote = { version = "1", default-features = false }

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = "1.0"
