name: docs
on:
  push:
   branches:
   - dev
   paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
      - .gitignore

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    env:
      # RUSTFLAGS: -D warnings
      CARGO_INCREMENTAL: 0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rust-src

    - name: Cache cargo output
      uses: Swatinem/rust-cache@v2

    - name: Build Rust Documentation
      env:
        RUSTDOCFLAGS: --cfg _doc -Zunstable-options --show-type-layout --enable-index-page
      run: cargo doc --features std,bytemuck,arbitrary,serde -Zrustdoc-map -Zrustdoc-scrape-examples

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
